### ISSUE TITLE
List of Appropriated Tasks 

### ISSUE THREAD

**Issue by alecedwards** [jgmac1106/youthzone#9] opened 2016-03-03 20:15 UTC
## Outreach

Google - Omar
Spotify - Sahil
Local (New Haven IO, Prometheus Labs, Continuity Control, Square 9, Datto) - Alec
CT Technology Council 
Mayor - Greg
## Recruitment

Local High Schools
Girls Who Code
Black Girls Code
Girl Scouts
## Registration

Contact Public Affairs about registration
## Information

Flyer Creation for distribution
Social Media(?)
## Logistics

Location
Equipment 
Judges
Prizes

**Comment by jgmac1106** [comment] 2016-03-08 21:16
Closing this as it is a dupe of #13

**Closed as completed by jgmac1106** 2016-03-08 21:16 UTC
